In [1]:
import pandas as pd
df = pd.read_csv('/content/sales_data_sample.csv', encoding='latin1')
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [2]:
print("DataFrame Info:")
df.info()
print("\nFirst 5 rows of the DataFrame:")
display(df.head())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB

First 5 rows of the DataFrame:

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [3]:
print("Missing values before handling:")
display(df.isnull().sum()[df.isnull().sum() > 0])

initial_columns = df.shape[1]
missing_percent = df.isnull().sum() / len(df) * 100
columns_to_drop = missing_percent[missing_percent > 50].index.tolist()
if columns_to_drop:
    df = df.drop(columns=columns_to_drop)
    print(f"Dropped columns due to high missing values (>50%): {columns_to_drop}")

print("\nMissing values after dropping high-missing columns:")
display(df.isnull().sum()[df.isnull().sum() > 0])
if df.isnull().sum().any():
    df.dropna(inplace=True)
    print("Dropped rows with any remaining missing values.")

final_columns = df.shape[1]
print(f"\nColumns before handling missing values: {initial_columns}, after: {final_columns}")
print("Final missing values check:")
display(df.isnull().sum()[df.isnull().sum() > 0])

Missing values before handling:

ADDRESSLINE2    2521
STATE           1486
POSTALCODE        76
TERRITORY       1074
dtype: int64

Dropped columns due to high missing values (>50%): ['ADDRESSLINE2', 'STATE']

Missing values after dropping high-missing columns:

POSTALCODE      76
TERRITORY     1074
dtype: int64

Dropped rows with any remaining missing values.

Columns before handling missing values: 25, after: 23
Final missing values check:

Series([], dtype: int64)

In [4]:
initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
final_rows = df.shape[0]
print(f"Number of rows before removing duplicates: {initial_rows}")
print(f"Number of rows after removing duplicates: {final_rows}")
print(f"Number of duplicate rows removed: {initial_rows - final_rows}")

Number of rows before removing duplicates: 1749
Number of rows after removing duplicates: 1749
Number of duplicate rows removed: 0

In [5]:
print("Unique values for 'PRODUCTLINE':")
print(df['PRODUCTLINE'].unique())

print("\nUnique values for 'DEALSIZE':")
print(df['DEALSIZE'].unique())

print("\nUnique values for 'CUSTOMERNAME' (first 10 unique):")
print(df['CUSTOMERNAME'].unique()[:10])
df['PRODUCTLINE'] = df['PRODUCTLINE'].str.title()
print("\n'PRODUCTLINE' after standardization (title case):")
print(df['PRODUCTLINE'].unique())
df['DEALSIZE'] = df['DEALSIZE'].str.title()
print("\n'DEALSIZE' after standardization (title case):")
print(df['DEALSIZE'].unique())

Unique values for 'PRODUCTLINE':
['Motorcycles' 'Classic Cars' 'Trucks and Buses' 'Vintage Cars' 'Planes'
 'Ships' 'Trains']

Unique values for 'DEALSIZE':
['Small' 'Medium' 'Large']

Unique values for 'CUSTOMERNAME' (first 10 unique):
['Reims Collectables' 'Lyon Souveniers' 'Daedalus Designs Imports'
 'Herkku Gifts' 'Auto Canal Petit' 'Australian Collectors, Co.'
 'La Rochelle Gifts' 'Toys of Finland, Co.' 'Baane Mini Imports'
 'Salzburg Collectables']

'PRODUCTLINE' after standardization (title case):
['Motorcycles' 'Classic Cars' 'Trucks And Buses' 'Vintage Cars' 'Planes'
 'Ships' 'Trains']

'DEALSIZE' after standardization (title case):
['Small' 'Medium' 'Large']

In [6]:
print("Data type of 'ORDERDATE' before conversion:", df['ORDERDATE'].dtype)
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])

print("Data type of 'ORDERDATE' after conversion:", df['ORDERDATE'].dtype)
print("First 5 'ORDERDATE' values after conversion:")
display(df['ORDERDATE'].head())

Data type of 'ORDERDATE' before conversion: object
Data type of 'ORDERDATE' after conversion: datetime64[ns]
First 5 'ORDERDATE' values after conversion:

1   2003-05-07
2   2003-07-01
6   2003-11-11
7   2003-11-18
9   2004-01-15
Name: ORDERDATE, dtype: datetime64[ns]

In [7]:
print("Original column names:")
print(df.columns.tolist())
df.columns = df.columns.str.lower().str.replace(' ', '_')

print("\nNew column names:")
print(df.columns.tolist())

Original column names:
['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'CITY', 'POSTALCODE', 'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE']

New column names:
['ordernumber', 'quantityordered', 'priceeach', 'orderlinenumber', 'sales', 'orderdate', 'status', 'qtr_id', 'month_id', 'year_id', 'productline', 'msrp', 'productcode', 'customername', 'phone', 'addressline1', 'city', 'postalcode', 'country', 'territory', 'contactlastname', 'contactfirstname', 'dealsize']

In [8]:
print("Data types before final check:")
df.info()
df['ordernumber'] = df['ordernumber'].astype(str)
for col in ['productline', 'productcode', 'customername', 'city', 'country', 'dealsize']:
    if col in df.columns and df[col].dtype == 'object':
        df[col] = df[col].astype('category')
for col in ['quantityordered', 'priceeach', 'sales', 'orderlinenumber']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

print("\nData types after final check and conversion:")
df.info()

Data types before final check:
<class 'pandas.core.frame.DataFrame'>
Index: 1749 entries, 1 to 2821
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ordernumber       1749 non-null   int64
 1   quantityordered   1749 non-null   int64
 2   priceeach         1749 non-null   float64
 3   orderlinenumber   1749 non-null   int64
 4   sales             1749 non-null   float64
 5   orderdate         1749 non-null   datetime64[ns]
 6   status            1749 non-null   object
 7   qtr_id            1749 non-null   int64
 8   month_id          1749 non-null   int64
 9   year_id           1749 non-null   int64
 10  productline       1749 non-null   object
 11  msrp              1749 non-null   int64
 12  productcode       1749 non-null   object
 13  customername      1749 non-null   object
 14  phone             1749 non-null   object
 15  addressline1      1749 non-null   object
 16  city              1749 non-null   object
 17  postalcode        1749 non-null   object
 18  country           1749 non-null   object
 19  territory         1749 non-null   object
 20  contactlastname   1749 non-null   object
 21  contactfirstname  1749 non-null   object
 22  dealsize          1749 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(7), object(13)
memory usage: 327.9+ KB

Data types after final check and conversion:
<class 'pandas.core.frame.DataFrame'>
Index: 1749 entries, 1 to 2821
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ordernumber       1749 non-null   object
 1   quantityordered   1749 non-null   int64
 2   priceeach         1749 non-null   float64
 3   orderlinenumber   1749 non-null   int64
 4   sales             1749 non-null   float64
 5   orderdate         1749 non-null   datetime64[ns]
 6   status            1749 non-null   object
 7   qtr_id            1749 non-null   int64
 8   month_id          1749 non-null   int64
 9   year_id           1749 non-null   int64
 10  productline       1749 non-null   category
 11  msrp              1749 non-null   int64
 12  productcode       1749 non-null   category
 13  customername      1749 non-null   category
 14  phone             1749 non-null   object
 15  addressline1      1749 non-null   object
 16  city              1749 non-null   category
 17  postalcode        1749 non-null   object
 18  country           1749 non-null   category
 19  territory         1749 non-null   object
 20  contactlastname   1749 non-null   object
 21  contactfirstname  1749 non-null   object
 22  dealsize          1749 non-null   category
dtypes: category(6), datetime64[ns](1), float64(2), int64(6), object(8)
memory usage: 266.2+ KB